include $(CLEAR_VARS)

LOCAL_MODULE := atari

LOCAL_SRC_FILES :=	$(CORE_DIR)/mame/drivers/atarigx2.c \
					$(CORE_DIR)/mame/video/atarigx2.c \
					$(CORE_DIR)/mame/drivers/arcadecl.c \
					$(CORE_DIR)/mame/video/arcadecl.c \
					$(CORE_DIR)/mame/drivers/asteroid.c \
					$(CORE_DIR)/mame/machine/asteroid.c \
					$(CORE_DIR)/mame/audio/asteroid.c \
					$(CORE_DIR)/mame/audio/llander.c \
					$(CORE_DIR)/mame/drivers/atarifb.c \
					$(CORE_DIR)/mame/machine/atarifb.c \
					$(CORE_DIR)/mame/audio/atarifb.c \
					$(CORE_DIR)/mame/video/atarifb.c \
					$(CORE_DIR)/mame/drivers/atarig1.c \
					$(CORE_DIR)/mame/video/atarig1.c \
					$(CORE_DIR)/mame/drivers/atarig42.c \
					$(CORE_DIR)/mame/video/atarig42.c \
					$(CORE_DIR)/mame/drivers/atarigt.c \
					$(CORE_DIR)/mame/video/atarigt.c \
					$(CORE_DIR)/mame/drivers/atarisy1.c \
					$(CORE_DIR)/mame/video/atarisy1.c \
					$(CORE_DIR)/mame/drivers/atarisy2.c \
					$(CORE_DIR)/mame/video/atarisy2.c \
					$(CORE_DIR)/mame/drivers/atetris.c \
					$(CORE_DIR)/mame/video/atetris.c \
					$(CORE_DIR)/mame/drivers/avalnche.c \
					$(CORE_DIR)/mame/audio/avalnche.c \
					$(CORE_DIR)/mame/drivers/badlands.c \
					$(CORE_DIR)/mame/video/badlands.c \
					$(CORE_DIR)/mame/drivers/batman.c \
					$(CORE_DIR)/mame/video/batman.c \
					$(CORE_DIR)/mame/drivers/beathead.c \
					$(CORE_DIR)/mame/video/beathead.c \
					$(CORE_DIR)/mame/drivers/blstroid.c \
					$(CORE_DIR)/mame/video/blstroid.c \
					$(CORE_DIR)/mame/drivers/boxer.c \
					$(CORE_DIR)/mame/drivers/bsktball.c \
					$(CORE_DIR)/mame/machine/bsktball.c \
					$(CORE_DIR)/mame/audio/bsktball.c \
					$(CORE_DIR)/mame/video/bsktball.c \
					$(CORE_DIR)/mame/drivers/bwidow.c \
					$(CORE_DIR)/mame/drivers/bzone.c \
					$(CORE_DIR)/mame/audio/bzone.c \
					$(CORE_DIR)/mame/drivers/canyon.c \
					$(CORE_DIR)/mame/audio/canyon.c \
					$(CORE_DIR)/mame/video/canyon.c \
					$(CORE_DIR)/mame/drivers/cball.c \
					$(CORE_DIR)/mame/drivers/ccastles.c \
					$(CORE_DIR)/mame/video/ccastles.c \
					$(CORE_DIR)/mame/drivers/centiped.c \
					$(CORE_DIR)/mame/video/centiped.c \
					$(CORE_DIR)/mame/drivers/cloak.c \
					$(CORE_DIR)/mame/video/cloak.c \
					$(CORE_DIR)/mame/drivers/cloud9.c \
					$(CORE_DIR)/mame/video/cloud9.c \
					$(CORE_DIR)/mame/drivers/cmmb.c \
					$(CORE_DIR)/mame/drivers/cojag.c \
					$(CORE_DIR)/mame/audio/jaguar.c \
					$(CORE_DIR)/mame/video/jaguar.c \
					$(CORE_DIR)/mame/drivers/copsnrob.c \
					$(CORE_DIR)/mame/machine/copsnrob.c \
					$(CORE_DIR)/mame/video/copsnrob.c \
					$(CORE_DIR)/mame/drivers/cyberbal.c \
					$(CORE_DIR)/mame/audio/cyberbal.c \
					$(CORE_DIR)/mame/video/cyberbal.c \
					$(CORE_DIR)/mame/drivers/destroyr.c \
					$(CORE_DIR)/mame/drivers/dragrace.c \
					$(CORE_DIR)/mame/audio/dragrace.c \
					$(CORE_DIR)/mame/video/dragrace.c \
					$(CORE_DIR)/mame/drivers/eprom.c \
					$(CORE_DIR)/mame/video/eprom.c \
					$(CORE_DIR)/mame/drivers/firefox.c \
					$(CORE_DIR)/mame/drivers/firetrk.c \
					$(CORE_DIR)/mame/audio/firetrk.c \
					$(CORE_DIR)/mame/video/firetrk.c \
					$(CORE_DIR)/mame/drivers/flyball.c \
					$(CORE_DIR)/mame/drivers/foodf.c \
					$(CORE_DIR)/mame/video/foodf.c \
					$(CORE_DIR)/mame/drivers/gauntlet.c \
					$(CORE_DIR)/mame/video/gauntlet.c \
					$(CORE_DIR)/mame/drivers/harddriv.c \
					$(CORE_DIR)/mame/machine/harddriv.c \
					$(CORE_DIR)/mame/audio/harddriv.c \
					$(CORE_DIR)/mame/video/harddriv.c \
					$(CORE_DIR)/mame/drivers/irobot.c \
					$(CORE_DIR)/mame/machine/irobot.c \
					$(CORE_DIR)/mame/video/irobot.c \
					$(CORE_DIR)/mame/drivers/jedi.c \
					$(CORE_DIR)/mame/audio/jedi.c \
					$(CORE_DIR)/mame/video/jedi.c \
					$(CORE_DIR)/mame/drivers/klax.c \
					$(CORE_DIR)/mame/video/klax.c \
					$(CORE_DIR)/mame/drivers/liberatr.c \
					$(CORE_DIR)/mame/video/liberatr.c \
					$(CORE_DIR)/mame/drivers/mediagx.c \
					$(CORE_DIR)/mame/drivers/metalmx.c \
					$(CORE_DIR)/mame/drivers/mgolf.c \
					$(CORE_DIR)/mame/drivers/mhavoc.c \
					$(CORE_DIR)/mame/machine/mhavoc.c \
					$(CORE_DIR)/mame/drivers/missile.c \
					$(CORE_DIR)/mame/drivers/nitedrvr.c \
					$(CORE_DIR)/mame/machine/nitedrvr.c \
					$(CORE_DIR)/mame/audio/nitedrvr.c \
					$(CORE_DIR)/mame/video/nitedrvr.c \
					$(CORE_DIR)/mame/drivers/offtwall.c \
					$(CORE_DIR)/mame/video/offtwall.c \
					$(CORE_DIR)/mame/drivers/orbit.c \
					$(CORE_DIR)/mame/audio/orbit.c \
					$(CORE_DIR)/mame/video/orbit.c \
					$(CORE_DIR)/mame/drivers/poolshrk.c \
					$(CORE_DIR)/mame/audio/poolshrk.c \
					$(CORE_DIR)/mame/video/poolshrk.c \
					$(CORE_DIR)/mame/drivers/quantum.c \
					$(CORE_DIR)/mame/drivers/rampart.c \
					$(CORE_DIR)/mame/video/rampart.c \
					$(CORE_DIR)/mame/drivers/relief.c \
					$(CORE_DIR)/mame/video/relief.c \
					$(CORE_DIR)/mame/drivers/runaway.c \
					$(CORE_DIR)/mame/video/runaway.c \
					$(CORE_DIR)/mame/drivers/sbrkout.c \
					$(CORE_DIR)/mame/drivers/shuuz.c \
					$(CORE_DIR)/mame/video/shuuz.c \
					$(CORE_DIR)/mame/drivers/skullxbo.c \
					$(CORE_DIR)/mame/video/skullxbo.c \
					$(CORE_DIR)/mame/drivers/skydiver.c \
					$(CORE_DIR)/mame/audio/skydiver.c \
					$(CORE_DIR)/mame/video/skydiver.c \
					$(CORE_DIR)/mame/drivers/skyraid.c \
					$(CORE_DIR)/mame/audio/skyraid.c \
					$(CORE_DIR)/mame/video/skyraid.c \
					$(CORE_DIR)/mame/drivers/sprint2.c \
					$(CORE_DIR)/mame/audio/sprint2.c \
					$(CORE_DIR)/mame/video/sprint2.c \
					$(CORE_DIR)/mame/drivers/sprint4.c \
					$(CORE_DIR)/mame/video/sprint4.c \
					$(CORE_DIR)/mame/audio/sprint4.c \
					$(CORE_DIR)/mame/drivers/sprint8.c \
					$(CORE_DIR)/mame/audio/sprint8.c \
					$(CORE_DIR)/mame/video/sprint8.c \
					$(CORE_DIR)/mame/drivers/starshp1.c \
					$(CORE_DIR)/mame/audio/starshp1.c \
					$(CORE_DIR)/mame/video/starshp1.c \
					$(CORE_DIR)/mame/drivers/starwars.c \
					$(CORE_DIR)/mame/machine/starwars.c \
					$(CORE_DIR)/mame/audio/starwars.c \
					$(CORE_DIR)/mame/drivers/subs.c \
					$(CORE_DIR)/mame/machine/subs.c \
					$(CORE_DIR)/mame/audio/subs.c \
					$(CORE_DIR)/mame/video/subs.c \
					$(CORE_DIR)/mame/drivers/tank8.c \
					$(CORE_DIR)/mame/audio/tank8.c \
					$(CORE_DIR)/mame/video/tank8.c \
					$(CORE_DIR)/mame/drivers/tempest.c \
					$(CORE_DIR)/mame/drivers/thunderj.c \
					$(CORE_DIR)/mame/video/thunderj.c \
					$(CORE_DIR)/mame/drivers/tomcat.c \
					$(CORE_DIR)/mame/drivers/toobin.c \
					$(CORE_DIR)/mame/video/toobin.c \
					$(CORE_DIR)/mame/drivers/tourtabl.c \
					$(CORE_DIR)/mame/video/tia.c \
					$(CORE_DIR)/mame/drivers/triplhnt.c \
					$(CORE_DIR)/mame/audio/triplhnt.c \
					$(CORE_DIR)/mame/video/triplhnt.c \
					$(CORE_DIR)/mame/drivers/tunhunt.c \
					$(CORE_DIR)/mame/video/tunhunt.c \
					$(CORE_DIR)/mame/drivers/ultratnk.c \
					$(CORE_DIR)/mame/video/ultratnk.c \
					$(CORE_DIR)/mame/drivers/videopin.c \
					$(CORE_DIR)/mame/audio/videopin.c \
					$(CORE_DIR)/mame/video/videopin.c \
					$(CORE_DIR)/mame/drivers/vindictr.c \
					$(CORE_DIR)/mame/video/vindictr.c \
					$(CORE_DIR)/mame/drivers/wolfpack.c \
					$(CORE_DIR)/mame/video/wolfpack.c \
					$(CORE_DIR)/mame/drivers/xybots.c \
					$(CORE_DIR)/mame/video/xybots.c \
					$(CORE_DIR)/mame/machine/asic65.c \
					$(CORE_DIR)/mame/machine/atari_vg.c \
					$(CORE_DIR)/mame/machine/atarigen.c \
					$(CORE_DIR)/mame/machine/mathbox.c \
					$(CORE_DIR)/mame/machine/slapstic.c \
					$(CORE_DIR)/mame/audio/atarijsa.c \
					$(CORE_DIR)/mame/audio/cage.c \
					$(CORE_DIR)/mame/audio/redbaron.c \
					$(CORE_DIR)/mame/video/atarimo.c \
					$(CORE_DIR)/mame/video/atarirle.c
					
LOCAL_CFLAGS := $(MAME_CFLAGS)

LOCAL_C_INCLUDES := $(MAME_C_INCLUDES)

LOCAL_CPP_EXTENSION := .c

include $(BUILD_STATIC_LIBRARY)