include $(CLEAR_VARS)

LOCAL_MODULE := taito

LOCAL_SRC_FILES :=	$(CORE_DIR)/mame/drivers/40love.c \
					$(CORE_DIR)/mame/video/40love.c \
					$(CORE_DIR)/mame/drivers/arkanoid.c \
					$(CORE_DIR)/mame/machine/arkanoid.c \
					$(CORE_DIR)/mame/video/arkanoid.c \
					$(CORE_DIR)/mame/drivers/ashnojoe.c \
					$(CORE_DIR)/mame/video/ashnojoe.c \
					$(CORE_DIR)/mame/drivers/asuka.c \
					$(CORE_DIR)/mame/machine/bonzeadv.c \
					$(CORE_DIR)/mame/video/asuka.c \
					$(CORE_DIR)/mame/drivers/bigevglf.c \
					$(CORE_DIR)/mame/machine/bigevglf.c \
					$(CORE_DIR)/mame/video/bigevglf.c \
					$(CORE_DIR)/mame/drivers/bking.c \
					$(CORE_DIR)/mame/video/bking.c \
					$(CORE_DIR)/mame/drivers/bublbobl.c \
					$(CORE_DIR)/mame/machine/bublbobl.c \
					$(CORE_DIR)/mame/video/bublbobl.c \
					$(CORE_DIR)/mame/drivers/buggychl.c \
					$(CORE_DIR)/mame/machine/buggychl.c \
					$(CORE_DIR)/mame/video/buggychl.c \
					$(CORE_DIR)/mame/drivers/cchance.c \
					$(CORE_DIR)/mame/drivers/chaknpop.c \
					$(CORE_DIR)/mame/machine/chaknpop.c \
					$(CORE_DIR)/mame/video/chaknpop.c \
					$(CORE_DIR)/mame/drivers/champbwl.c \
					$(CORE_DIR)/mame/drivers/changela.c \
					$(CORE_DIR)/mame/video/changela.c \
					$(CORE_DIR)/mame/drivers/crbaloon.c \
					$(CORE_DIR)/mame/video/crbaloon.c \
					$(CORE_DIR)/mame/audio/crbaloon.c \
					$(CORE_DIR)/mame/drivers/cyclemb.c \
					$(CORE_DIR)/mame/drivers/darius.c \
					$(CORE_DIR)/mame/video/darius.c \
					$(CORE_DIR)/mame/drivers/darkmist.c \
					$(CORE_DIR)/mame/video/darkmist.c \
					$(CORE_DIR)/mame/drivers/exzisus.c \
					$(CORE_DIR)/mame/video/exzisus.c \
					$(CORE_DIR)/mame/drivers/fgoal.c \
					$(CORE_DIR)/mame/video/fgoal.c \
					$(CORE_DIR)/mame/drivers/flstory.c \
					$(CORE_DIR)/mame/machine/flstory.c \
					$(CORE_DIR)/mame/video/flstory.c \
					$(CORE_DIR)/mame/drivers/galastrm.c \
					$(CORE_DIR)/mame/video/galastrm.c \
					$(CORE_DIR)/mame/drivers/gladiatr.c \
					$(CORE_DIR)/mame/video/gladiatr.c \
					$(CORE_DIR)/mame/drivers/grchamp.c \
					$(CORE_DIR)/mame/audio/grchamp.c \
					$(CORE_DIR)/mame/video/grchamp.c \
					$(CORE_DIR)/mame/drivers/groundfx.c \
					$(CORE_DIR)/mame/video/groundfx.c \
					$(CORE_DIR)/mame/drivers/gsword.c \
					$(CORE_DIR)/mame/machine/tait8741.c \
					$(CORE_DIR)/mame/video/gsword.c \
					$(CORE_DIR)/mame/drivers/gunbustr.c \
					$(CORE_DIR)/mame/video/gunbustr.c \
					$(CORE_DIR)/mame/drivers/halleys.c \
					$(CORE_DIR)/mame/drivers/jollyjgr.c \
					$(CORE_DIR)/mame/drivers/ksayakyu.c \
					$(CORE_DIR)/mame/video/ksayakyu.c \
					$(CORE_DIR)/mame/drivers/lgp.c \
					$(CORE_DIR)/mame/drivers/lkage.c \
					$(CORE_DIR)/mame/machine/lkage.c \
					$(CORE_DIR)/mame/video/lkage.c \
					$(CORE_DIR)/mame/drivers/lsasquad.c \
					$(CORE_DIR)/mame/machine/lsasquad.c \
					$(CORE_DIR)/mame/video/lsasquad.c \
					$(CORE_DIR)/mame/drivers/marinedt.c \
					$(CORE_DIR)/mame/drivers/mexico86.c \
					$(CORE_DIR)/mame/machine/mexico86.c \
					$(CORE_DIR)/mame/video/mexico86.c \
					$(CORE_DIR)/mame/drivers/minivadr.c \
					$(CORE_DIR)/mame/drivers/missb2.c \
					$(CORE_DIR)/mame/drivers/mlanding.c \
					$(CORE_DIR)/mame/drivers/msisaac.c \
					$(CORE_DIR)/mame/video/msisaac.c \
					$(CORE_DIR)/mame/drivers/ninjaw.c \
					$(CORE_DIR)/mame/video/ninjaw.c \
					$(CORE_DIR)/mame/drivers/nycaptor.c \
					$(CORE_DIR)/mame/machine/nycaptor.c \
					$(CORE_DIR)/mame/video/nycaptor.c \
					$(CORE_DIR)/mame/drivers/opwolf.c \
					$(CORE_DIR)/mame/machine/opwolf.c \
					$(CORE_DIR)/mame/drivers/othunder.c \
					$(CORE_DIR)/mame/video/othunder.c \
					$(CORE_DIR)/mame/drivers/pitnrun.c \
					$(CORE_DIR)/mame/machine/pitnrun.c \
					$(CORE_DIR)/mame/video/pitnrun.c \
					$(CORE_DIR)/mame/drivers/qix.c \
					$(CORE_DIR)/mame/machine/qix.c \
					$(CORE_DIR)/mame/audio/qix.c \
					$(CORE_DIR)/mame/video/qix.c \
					$(CORE_DIR)/mame/drivers/rainbow.c \
					$(CORE_DIR)/mame/machine/rainbow.c \
					$(CORE_DIR)/mame/drivers/rastan.c \
					$(CORE_DIR)/mame/video/rastan.c \
					$(CORE_DIR)/mame/drivers/retofinv.c \
					$(CORE_DIR)/mame/machine/retofinv.c \
					$(CORE_DIR)/mame/video/retofinv.c \
					$(CORE_DIR)/mame/drivers/rollrace.c \
					$(CORE_DIR)/mame/video/rollrace.c \
					$(CORE_DIR)/mame/drivers/sbowling.c \
					$(CORE_DIR)/mame/drivers/slapshot.c \
					$(CORE_DIR)/mame/video/slapshot.c \
					$(CORE_DIR)/mame/drivers/ssrj.c \
					$(CORE_DIR)/mame/video/ssrj.c \
					$(CORE_DIR)/mame/drivers/superchs.c \
					$(CORE_DIR)/mame/video/superchs.c \
					$(CORE_DIR)/mame/drivers/superqix.c \
					$(CORE_DIR)/mame/video/superqix.c \
					$(CORE_DIR)/mame/drivers/taito_b.c \
					$(CORE_DIR)/mame/video/taito_b.c \
					$(CORE_DIR)/mame/drivers/taito_f2.c \
					$(CORE_DIR)/mame/video/taito_f2.c \
					$(CORE_DIR)/mame/drivers/taito_f3.c \
					$(CORE_DIR)/mame/video/taito_f3.c \
					$(CORE_DIR)/mame/audio/taito_en.c \
					$(CORE_DIR)/mame/drivers/taito_h.c \
					$(CORE_DIR)/mame/video/taito_h.c \
					$(CORE_DIR)/mame/drivers/taito_l.c \
					$(CORE_DIR)/mame/video/taito_l.c \
					$(CORE_DIR)/mame/drivers/taito_x.c \
					$(CORE_DIR)/mame/machine/cchip.c \
					$(CORE_DIR)/mame/drivers/taito_z.c \
					$(CORE_DIR)/mame/video/taito_z.c \
					$(CORE_DIR)/mame/drivers/taito_o.c \
					$(CORE_DIR)/mame/video/taito_o.c \
					$(CORE_DIR)/mame/drivers/taitoair.c \
					$(CORE_DIR)/mame/video/taitoair.c \
					$(CORE_DIR)/mame/drivers/taitojc.c \
					$(CORE_DIR)/mame/video/taitojc.c \
					$(CORE_DIR)/mame/drivers/taitopjc.c \
					$(CORE_DIR)/mame/drivers/taitosj.c \
					$(CORE_DIR)/mame/machine/taitosj.c \
					$(CORE_DIR)/mame/video/taitosj.c \
					$(CORE_DIR)/mame/drivers/taitotz.c \
					$(CORE_DIR)/mame/drivers/taitowlf.c \
					$(CORE_DIR)/mame/drivers/tnzs.c \
					$(CORE_DIR)/mame/machine/tnzs.c \
					$(CORE_DIR)/mame/video/tnzs.c \
					$(CORE_DIR)/mame/drivers/topspeed.c \
					$(CORE_DIR)/mame/video/topspeed.c \
					$(CORE_DIR)/mame/drivers/tsamurai.c \
					$(CORE_DIR)/mame/video/tsamurai.c \
					$(CORE_DIR)/mame/drivers/undrfire.c \
					$(CORE_DIR)/mame/video/undrfire.c \
					$(CORE_DIR)/mame/drivers/volfied.c \
					$(CORE_DIR)/mame/machine/volfied.c \
					$(CORE_DIR)/mame/video/volfied.c \
					$(CORE_DIR)/mame/drivers/warriorb.c \
					$(CORE_DIR)/mame/video/warriorb.c \
					$(CORE_DIR)/mame/drivers/wgp.c \
					$(CORE_DIR)/mame/video/wgp.c \
					$(CORE_DIR)/mame/audio/taitosnd.c \
					$(CORE_DIR)/mame/audio/t5182.c \
					$(CORE_DIR)/mame/machine/taitoio.c \
					$(CORE_DIR)/mame/video/taitoic.c \
					$(CORE_DIR)/mame/audio/taito_zm.c
					
LOCAL_CFLAGS := $(MAME_CFLAGS)

LOCAL_C_INCLUDES := $(MAME_C_INCLUDES)

LOCAL_CPP_EXTENSION := .c

include $(BUILD_STATIC_LIBRARY)