include $(CLEAR_VARS)

LOCAL_MODULE := konami

LOCAL_SRC_FILES :=	$(CORE_DIR)/mame/drivers/88games.c \
					$(CORE_DIR)/mame/video/88games.c \
					$(CORE_DIR)/mame/drivers/ajax.c \
					$(CORE_DIR)/mame/machine/ajax.c \
					$(CORE_DIR)/mame/video/ajax.c \
					$(CORE_DIR)/mame/drivers/aliens.c \
					$(CORE_DIR)/mame/video/aliens.c \
					$(CORE_DIR)/mame/drivers/asterix.c \
					$(CORE_DIR)/mame/video/asterix.c \
					$(CORE_DIR)/mame/drivers/battlnts.c \
					$(CORE_DIR)/mame/video/battlnts.c \
					$(CORE_DIR)/mame/drivers/bishi.c \
					$(CORE_DIR)/mame/video/bishi.c \
					$(CORE_DIR)/mame/drivers/bladestl.c \
					$(CORE_DIR)/mame/video/bladestl.c \
					$(CORE_DIR)/mame/drivers/blockhl.c \
					$(CORE_DIR)/mame/video/blockhl.c \
					$(CORE_DIR)/mame/drivers/bottom9.c \
					$(CORE_DIR)/mame/video/bottom9.c \
					$(CORE_DIR)/mame/drivers/chqflag.c \
					$(CORE_DIR)/mame/video/chqflag.c \
					$(CORE_DIR)/mame/drivers/circusc.c \
					$(CORE_DIR)/mame/video/circusc.c \
					$(CORE_DIR)/mame/drivers/combatsc.c \
					$(CORE_DIR)/mame/video/combatsc.c \
					$(CORE_DIR)/mame/drivers/contra.c \
					$(CORE_DIR)/mame/video/contra.c \
					$(CORE_DIR)/mame/drivers/crimfght.c \
					$(CORE_DIR)/mame/video/crimfght.c \
					$(CORE_DIR)/mame/drivers/dbz.c \
					$(CORE_DIR)/mame/video/dbz.c \
					$(CORE_DIR)/mame/drivers/ddribble.c \
					$(CORE_DIR)/mame/video/ddribble.c \
					$(CORE_DIR)/mame/drivers/djmain.c \
					$(CORE_DIR)/mame/video/djmain.c \
					$(CORE_DIR)/mame/drivers/fastfred.c \
					$(CORE_DIR)/mame/video/fastfred.c \
					$(CORE_DIR)/mame/drivers/fastlane.c \
					$(CORE_DIR)/mame/video/fastlane.c \
					$(CORE_DIR)/mame/drivers/finalizr.c \
					$(CORE_DIR)/mame/video/finalizr.c \
					$(CORE_DIR)/mame/drivers/firebeat.c \
					$(CORE_DIR)/mame/drivers/flkatck.c \
					$(CORE_DIR)/mame/video/flkatck.c \
					$(CORE_DIR)/mame/drivers/gberet.c \
					$(CORE_DIR)/mame/video/gberet.c \
					$(CORE_DIR)/mame/drivers/gbusters.c \
					$(CORE_DIR)/mame/video/gbusters.c \
					$(CORE_DIR)/mame/drivers/gijoe.c \
					$(CORE_DIR)/mame/video/gijoe.c \
					$(CORE_DIR)/mame/drivers/gradius3.c \
					$(CORE_DIR)/mame/video/gradius3.c \
					$(CORE_DIR)/mame/drivers/gticlub.c \
					$(CORE_DIR)/mame/video/gticlub.c \
					$(CORE_DIR)/mame/drivers/gyruss.c \
					$(CORE_DIR)/mame/video/gyruss.c \
					$(CORE_DIR)/mame/drivers/hcastle.c \
					$(CORE_DIR)/mame/video/hcastle.c \
					$(CORE_DIR)/mame/drivers/hexion.c \
					$(CORE_DIR)/mame/video/hexion.c \
					$(CORE_DIR)/mame/drivers/hornet.c \
					$(CORE_DIR)/mame/machine/konppc.c \
					$(CORE_DIR)/mame/drivers/hyperspt.c \
					$(CORE_DIR)/mame/video/hyperspt.c \
					$(CORE_DIR)/mame/drivers/ironhors.c \
					$(CORE_DIR)/mame/video/ironhors.c \
					$(CORE_DIR)/mame/drivers/jackal.c \
					$(CORE_DIR)/mame/video/jackal.c \
					$(CORE_DIR)/mame/drivers/jailbrek.c \
					$(CORE_DIR)/mame/video/jailbrek.c \
					$(CORE_DIR)/mame/drivers/junofrst.c \
					$(CORE_DIR)/mame/drivers/konamigq.c \
					$(CORE_DIR)/mame/drivers/konamigv.c \
					$(CORE_DIR)/mame/drivers/konamigx.c \
					$(CORE_DIR)/mame/machine/konamigx.c \
					$(CORE_DIR)/mame/video/konamigx.c \
					$(CORE_DIR)/mame/drivers/konamim2.c \
					$(CORE_DIR)/mame/drivers/kongambl.c \
					$(CORE_DIR)/mame/drivers/ksys573.c \
					$(CORE_DIR)/mame/machine/zs01.c \
					$(CORE_DIR)/mame/drivers/twinkle.c \
					$(CORE_DIR)/mame/drivers/labyrunr.c \
					$(CORE_DIR)/mame/video/labyrunr.c \
					$(CORE_DIR)/mame/drivers/lethal.c \
					$(CORE_DIR)/mame/video/lethal.c \
					$(CORE_DIR)/mame/drivers/mainevt.c \
					$(CORE_DIR)/mame/video/mainevt.c \
					$(CORE_DIR)/mame/drivers/megazone.c \
					$(CORE_DIR)/mame/video/megazone.c \
					$(CORE_DIR)/mame/drivers/mikie.c \
					$(CORE_DIR)/mame/video/mikie.c \
					$(CORE_DIR)/mame/drivers/mogura.c \
					$(CORE_DIR)/mame/drivers/moo.c \
					$(CORE_DIR)/mame/video/moo.c \
					$(CORE_DIR)/mame/drivers/mystwarr.c \
					$(CORE_DIR)/mame/video/mystwarr.c \
					$(CORE_DIR)/mame/drivers/nemesis.c \
					$(CORE_DIR)/mame/video/nemesis.c \
					$(CORE_DIR)/mame/drivers/nwk-tr.c \
					$(CORE_DIR)/mame/drivers/overdriv.c \
					$(CORE_DIR)/mame/video/overdriv.c \
					$(CORE_DIR)/mame/drivers/pandoras.c \
					$(CORE_DIR)/mame/video/pandoras.c \
					$(CORE_DIR)/mame/drivers/parodius.c \
					$(CORE_DIR)/mame/video/parodius.c \
					$(CORE_DIR)/mame/drivers/pingpong.c \
					$(CORE_DIR)/mame/video/pingpong.c \
					$(CORE_DIR)/mame/drivers/plygonet.c \
					$(CORE_DIR)/mame/video/plygonet.c \
					$(CORE_DIR)/mame/drivers/pooyan.c \
					$(CORE_DIR)/mame/video/pooyan.c \
					$(CORE_DIR)/mame/drivers/qdrmfgp.c \
					$(CORE_DIR)/mame/video/qdrmfgp.c \
					$(CORE_DIR)/mame/drivers/rockrage.c \
					$(CORE_DIR)/mame/video/rockrage.c \
					$(CORE_DIR)/mame/drivers/rocnrope.c \
					$(CORE_DIR)/mame/video/rocnrope.c \
					$(CORE_DIR)/mame/drivers/rollerg.c \
					$(CORE_DIR)/mame/video/rollerg.c \
					$(CORE_DIR)/mame/drivers/rungun.c \
					$(CORE_DIR)/mame/video/rungun.c \
					$(CORE_DIR)/mame/drivers/sbasketb.c \
					$(CORE_DIR)/mame/video/sbasketb.c \
					$(CORE_DIR)/mame/drivers/scobra.c \
					$(CORE_DIR)/mame/drivers/scotrsht.c \
					$(CORE_DIR)/mame/video/scotrsht.c \
					$(CORE_DIR)/mame/drivers/scramble.c \
					$(CORE_DIR)/mame/machine/scramble.c \
					$(CORE_DIR)/mame/audio/scramble.c \
					$(CORE_DIR)/mame/drivers/shaolins.c \
					$(CORE_DIR)/mame/video/shaolins.c \
					$(CORE_DIR)/mame/drivers/simpsons.c \
					$(CORE_DIR)/mame/machine/simpsons.c \
					$(CORE_DIR)/mame/video/simpsons.c \
					$(CORE_DIR)/mame/drivers/spy.c \
					$(CORE_DIR)/mame/video/spy.c \
					$(CORE_DIR)/mame/drivers/surpratk.c \
					$(CORE_DIR)/mame/video/surpratk.c \
					$(CORE_DIR)/mame/drivers/tgtpanic.c \
					$(CORE_DIR)/mame/drivers/thunderx.c \
					$(CORE_DIR)/mame/video/thunderx.c \
					$(CORE_DIR)/mame/drivers/timeplt.c \
					$(CORE_DIR)/mame/audio/timeplt.c \
					$(CORE_DIR)/mame/video/timeplt.c \
					$(CORE_DIR)/mame/drivers/tmnt.c \
					$(CORE_DIR)/mame/video/tmnt.c \
					$(CORE_DIR)/mame/drivers/tp84.c \
					$(CORE_DIR)/mame/video/tp84.c \
					$(CORE_DIR)/mame/drivers/trackfld.c \
					$(CORE_DIR)/mame/machine/konami1.c \
					$(CORE_DIR)/mame/audio/trackfld.c \
					$(CORE_DIR)/mame/video/trackfld.c \
					$(CORE_DIR)/mame/drivers/tutankhm.c \
					$(CORE_DIR)/mame/video/tutankhm.c \
					$(CORE_DIR)/mame/drivers/twin16.c \
					$(CORE_DIR)/mame/video/twin16.c \
					$(CORE_DIR)/mame/drivers/ultrsprt.c \
					$(CORE_DIR)/mame/drivers/ultraman.c \
					$(CORE_DIR)/mame/video/ultraman.c \
					$(CORE_DIR)/mame/drivers/vendetta.c \
					$(CORE_DIR)/mame/video/vendetta.c \
					$(CORE_DIR)/mame/drivers/viper.c \
					$(CORE_DIR)/mame/drivers/wecleman.c \
					$(CORE_DIR)/mame/video/wecleman.c \
					$(CORE_DIR)/mame/drivers/xexex.c \
					$(CORE_DIR)/mame/video/xexex.c \
					$(CORE_DIR)/mame/drivers/xmen.c \
					$(CORE_DIR)/mame/video/xmen.c \
					$(CORE_DIR)/mame/drivers/yiear.c \
					$(CORE_DIR)/mame/video/yiear.c \
					$(CORE_DIR)/mame/drivers/zr107.c \
					$(CORE_DIR)/mame/video/konamiic.c \
					$(CORE_DIR)/mame/video/konicdev.c
					
LOCAL_CFLAGS := $(MAME_CFLAGS)

LOCAL_C_INCLUDES := $(MAME_C_INCLUDES)

LOCAL_CPP_EXTENSION := .c

include $(BUILD_STATIC_LIBRARY)