include $(CLEAR_VARS)

LOCAL_MODULE := libemu

LOCAL_SRC_FILES :=	$(CORE_DIR)/emu/attotime.c \
					$(CORE_DIR)/emu/audit.c \
					$(CORE_DIR)/emu/cheat.c \
					$(CORE_DIR)/emu/clifront.c \
					$(CORE_DIR)/emu/config.c \
					$(CORE_DIR)/emu/crsshair.c \
					$(CORE_DIR)/emu/debugger.c \
					$(CORE_DIR)/emu/devcb.c \
					$(CORE_DIR)/emu/devcpu.c \
					$(CORE_DIR)/emu/devimage.c \
					$(CORE_DIR)/emu/devlegcy.c \
					$(CORE_DIR)/emu/devintrf.c \
					$(CORE_DIR)/emu/didisasm.c \
					$(CORE_DIR)/emu/diexec.c \
					$(CORE_DIR)/emu/diimage.c \
					$(CORE_DIR)/emu/dimemory.c \
					$(CORE_DIR)/emu/dinvram.c \
					$(CORE_DIR)/emu/disound.c \
					$(CORE_DIR)/emu/distate.c \
					$(CORE_DIR)/emu/drawgfx.c \
					$(CORE_DIR)/emu/driver.c \
					$(CORE_DIR)/emu/emualloc.c \
					$(CORE_DIR)/emu/emucore.c \
					$(CORE_DIR)/emu/emuopts.c \
					$(CORE_DIR)/emu/emupal.c \
					$(CORE_DIR)/emu/fileio.c \
					$(CORE_DIR)/emu/hash.c \
					$(CORE_DIR)/emu/hashfile.c \
					$(CORE_DIR)/emu/image.c \
					$(CORE_DIR)/emu/info.c \
					$(CORE_DIR)/emu/input.c \
					$(CORE_DIR)/emu/inputseq.c \
					$(CORE_DIR)/emu/inptport.c \
					$(CORE_DIR)/emu/ioprocs.c \
					$(CORE_DIR)/emu/mame.c \
					$(CORE_DIR)/emu/machine.c \
					$(CORE_DIR)/emu/mconfig.c \
					$(CORE_DIR)/emu/memory.c \
					$(CORE_DIR)/emu/output.c \
					$(CORE_DIR)/emu/render.c \
					$(CORE_DIR)/emu/rendfont.c \
					$(CORE_DIR)/emu/rendlay.c \
					$(CORE_DIR)/emu/rendutil.c \
					$(CORE_DIR)/emu/romload.c \
					$(CORE_DIR)/emu/schedule.c \
					$(CORE_DIR)/emu/softlist.c \
					$(CORE_DIR)/emu/sound.c \
					$(CORE_DIR)/emu/state.c \
					$(CORE_DIR)/emu/streams.c \
					$(CORE_DIR)/emu/tilemap.c \
					$(CORE_DIR)/emu/timer.c \
					$(CORE_DIR)/emu/ui.c \
					$(CORE_DIR)/emu/uigfx.c \
					$(CORE_DIR)/emu/uiimage.c \
					$(CORE_DIR)/emu/uiinput.c \
					$(CORE_DIR)/emu/uimenu.c \
					$(CORE_DIR)/emu/validity.c \
					$(CORE_DIR)/emu/video.c \
					$(CORE_DIR)/emu/watchdog.c \
					$(CORE_DIR)/emu/debug/debugcmd.c \
					$(CORE_DIR)/emu/debug/debugcmt.c \
					$(CORE_DIR)/emu/debug/debugcon.c \
					$(CORE_DIR)/emu/debug/debugcpu.c \
					$(CORE_DIR)/emu/debug/debughlp.c \
					$(CORE_DIR)/emu/debug/debugvw.c \
					$(CORE_DIR)/emu/debug/dvdisasm.c \
					$(CORE_DIR)/emu/debug/dvmemory.c \
					$(CORE_DIR)/emu/debug/dvstate.c \
					$(CORE_DIR)/emu/debug/dvtext.c \
					$(CORE_DIR)/emu/debug/express.c \
					$(CORE_DIR)/emu/debug/textbuf.c \
					$(CORE_DIR)/emu/debugint/debugint.c \
					$(CORE_DIR)/emu/sound/filter.c \
					$(CORE_DIR)/emu/sound/flt_vol.c \
					$(CORE_DIR)/emu/sound/flt_rc.c \
					$(CORE_DIR)/emu/sound/wavwrite.c \
					$(CORE_DIR)/emu/audio/generic.c \
					$(CORE_DIR)/emu/drivers/empty.c \
					$(CORE_DIR)/emu/machine/53c810.c \
					$(CORE_DIR)/emu/machine/6532riot.c \
					$(CORE_DIR)/emu/machine/6522via.c \
					$(CORE_DIR)/emu/machine/6526cia.c \
					$(CORE_DIR)/emu/machine/6821pia.c \
					$(CORE_DIR)/emu/machine/6840ptm.c \
					$(CORE_DIR)/emu/machine/6850acia.c \
					$(CORE_DIR)/emu/machine/68681.c \
					$(CORE_DIR)/emu/machine/7474.c \
					$(CORE_DIR)/emu/machine/74123.c \
					$(CORE_DIR)/emu/machine/74148.c \
					$(CORE_DIR)/emu/machine/74153.c \
					$(CORE_DIR)/emu/machine/74181.c \
					$(CORE_DIR)/emu/machine/8042kbdc.c \
					$(CORE_DIR)/emu/machine/8237dma.c \
					$(CORE_DIR)/emu/machine/8257dma.c \
					$(CORE_DIR)/emu/machine/8255ppi.c \
					$(CORE_DIR)/emu/machine/adc083x.c \
					$(CORE_DIR)/emu/machine/adc1038.c \
					$(CORE_DIR)/emu/machine/adc1213x.c \
					$(CORE_DIR)/emu/machine/am53cf96.c \
					$(CORE_DIR)/emu/machine/at28c16.c \
					$(CORE_DIR)/emu/machine/cdp1852.c \
					$(CORE_DIR)/emu/machine/ds1302.c \
					$(CORE_DIR)/emu/machine/ds2401.c \
					$(CORE_DIR)/emu/machine/ds2404.c \
					$(CORE_DIR)/emu/machine/eeprom.c \
					$(CORE_DIR)/emu/machine/f3853.c \
					$(CORE_DIR)/emu/machine/generic.c \
					$(CORE_DIR)/emu/machine/i8243.c \
					$(CORE_DIR)/emu/machine/i8255a.c \
					$(CORE_DIR)/emu/machine/i2cmem.c \
					$(CORE_DIR)/emu/machine/idectrl.c \
					$(CORE_DIR)/emu/machine/ins8154.c \
					$(CORE_DIR)/emu/machine/ins8250.c \
					$(CORE_DIR)/emu/machine/intelfsh.c \
					$(CORE_DIR)/emu/machine/k033906.c \
					$(CORE_DIR)/emu/machine/k056230.c \
					$(CORE_DIR)/emu/machine/latch8.c \
					$(CORE_DIR)/emu/machine/ldcore.c \
					$(CORE_DIR)/emu/machine/ldpr8210.c \
					$(CORE_DIR)/emu/machine/ldv1000.c \
					$(CORE_DIR)/emu/machine/ldvp931.c \
					$(CORE_DIR)/emu/machine/mb14241.c \
					$(CORE_DIR)/emu/machine/mb3773.c \
					$(CORE_DIR)/emu/machine/mb87078.c \
					$(CORE_DIR)/emu/machine/mc146818.c \
					$(CORE_DIR)/emu/machine/microtch.c \
					$(CORE_DIR)/emu/machine/msm6242.c \
					$(CORE_DIR)/emu/machine/pc16552d.c \
					$(CORE_DIR)/emu/machine/pci.c \
					$(CORE_DIR)/emu/machine/pic8259.c \
					$(CORE_DIR)/emu/machine/pit8253.c \
					$(CORE_DIR)/emu/machine/pd4990a.c \
					$(CORE_DIR)/emu/machine/roc10937.c \
					$(CORE_DIR)/emu/machine/rp5h01.c \
					$(CORE_DIR)/emu/machine/rtc65271.c \
					$(CORE_DIR)/emu/machine/scsi.c \
					$(CORE_DIR)/emu/machine/scsicd.c \
					$(CORE_DIR)/emu/machine/scsidev.c \
					$(CORE_DIR)/emu/machine/scsihd.c \
					$(CORE_DIR)/emu/machine/cr589.c \
					$(CORE_DIR)/emu/machine/smc91c9x.c \
					$(CORE_DIR)/emu/machine/timekpr.c \
					$(CORE_DIR)/emu/machine/tmp68301.c \
					$(CORE_DIR)/emu/machine/tms6100.c \
					$(CORE_DIR)/emu/machine/upd4701.c \
					$(CORE_DIR)/emu/machine/wd33c93.c \
					$(CORE_DIR)/emu/machine/x2212.c \
					$(CORE_DIR)/emu/machine/x76f041.c \
					$(CORE_DIR)/emu/machine/x76f100.c \
					$(CORE_DIR)/emu/machine/z80ctc.c \
					$(CORE_DIR)/emu/machine/z80dart.c \
					$(CORE_DIR)/emu/machine/z80dma.c \
					$(CORE_DIR)/emu/machine/z80pio.c \
					$(CORE_DIR)/emu/machine/z80sio.c \
					$(CORE_DIR)/emu/machine/z80sti.c \
					$(CORE_DIR)/emu/video/generic.c \
					$(CORE_DIR)/emu/video/hd63484.c \
					$(CORE_DIR)/emu/video/mc6845.c \
					$(CORE_DIR)/emu/video/pc_vga.c \
					$(CORE_DIR)/emu/video/pc_video.c \
					$(CORE_DIR)/emu/video/poly.c \
					$(CORE_DIR)/emu/video/resnet.c \
					$(CORE_DIR)/emu/video/rgbutil.c \
					$(CORE_DIR)/emu/video/s2636.c \
					$(CORE_DIR)/emu/video/saa5050.c \
					$(CORE_DIR)/emu/video/tlc34076.c \
					$(CORE_DIR)/emu/video/tms34061.c \
					$(CORE_DIR)/emu/video/tms9927.c \
					$(CORE_DIR)/emu/video/tms9928a.c \
					$(CORE_DIR)/emu/video/v9938.c \
					$(CORE_DIR)/emu/video/vector.c \
					$(CORE_DIR)/emu/video/voodoo.c

					
LOCAL_CFLAGS := $(MAME_CFLAGS)

LOCAL_C_INCLUDES := $(MAME_C_INCLUDES)

LOCAL_CPP_EXTENSION := .c

include $(BUILD_STATIC_LIBRARY)